### ISSUE TITLE
Field 'timecreated' doesn't have a default value

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroMoodle#2]
Avec la version 1.0.3 a la création dans moodle d'un nouvel établissement.

erreur mysql :
mysql.connector.errors.DatabaseError: 1364 (HY000): Field 'timecreated' doesn't have a default value

`[ERROR] [root] Une erreur inattendue s'est produite
Traceback (most recent call last):
  File "/home/esco/.pex/install/mysql_connector_python-8.0.15-cp35-cp35m-manylinux1_x86_64.whl.a1853495a7f1bc338372d7d2c2e5bd3df591a512/mysql_connector_python-8.0.15-cp35-cp35m-manylinux1_x86_64.whl/mysql/connector/connection_cext.py", line 395, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Field 'timecreated' doesn't have a default value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esco/.pex/install/synchromoodle-1.0.3-py3-none-any.whl.82537d3c1e085194b8a7daf4100abcf34e884f77/synchromoodle-1.0.3-py3-none-any.whl/synchromoodle/__main__.py", line 61, in main
    action_func(config, action, arguments)
  File "/home/esco/.pex/install/synchromoodle-1.0.3-py3-none-any.whl.82537d3c1e085194b8a7daf4100abcf34e884f77/synchromoodle-1.0.3-py3-none-any.whl/synchromoodle/actions.py", line 41, in default
    etablissement_context = synchronizer.handle_etablissement(uai, log=etablissement_log)
  File "/home/esco/.pex/install/synchromoodle-1.0.3-py3-none-any.whl.82537d3c1e085194b8a7daf4100abcf34e884f77/synchromoodle-1.0.3-py3-none-any.whl/synchromoodle/synchronizer.py", line 195, in handle_etablissement
    structure_ldap.siren, context.etablissement_theme)
  File "/home/esco/.pex/install/synchromoodle-1.0.3-py3-none-any.whl.82537d3c1e085194b8a7daf4100abcf34e884f77/synchromoodle-1.0.3-py3-none-any.whl/synchromoodle/synchronizer.py", line 888, in insert_moodle_structure
    sub_page_pattern, default_region, default_weight)
  File "/home/esco/.pex/install/synchromoodle-1.0.3-py3-none-any.whl.82537d3c1e085194b8a7daf4100abcf34e884f77/synchromoodle-1.0.3-py3-none-any.whl/synchromoodle/dbutils.py", line 956, in insert_moodle_block
    'default_weight': default_weight})
  File "/home/esco/.pex/install/mysql_connector_python-8.0.15-cp35-cp35m-manylinux1_x86_64.whl.a1853495a7f1bc338372d7d2c2e5bd3df591a512/mysql_connector_python-8.0.15-cp35-cp35m-manylinux1_x86_64.whl/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/esco/.pex/install/mysql_connector_python-8.0.15-cp35-cp35m-manylinux1_x86_64.whl.a1853495a7f1bc338372d7d2c2e5bd3df591a512/mysql_connector_python-8.0.15-cp35-cp35m-manylinux1_x86_64.whl/mysql/connector/connection_cext.py", line 398, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 1364 (HY000): Field 'timecreated' doesn't have a default value
[INFO] [root] Fin de l'action default (id=academique)
[INFO] [root] Terminé
`

**Comment by vcastro45** [comment]
Après vérification, nous avons bien un test unitaire qui test le bon fonctionnement de cette fonction.
Quelle est la version de MariaDB sur laquelle vous travaillez ?
Depuis MariaDB 10.0.1, les champs `DATETIME` prennent la valeur `CURRENT_TIMESTAMP` par defaut.

**Comment by jgribonvald** [comment]
la version est une 10.1.x
et la configuration pour cette version est très proche de celle-ci: https://github.com/GIP-RECIA/docker-mariadb

**Comment by vcastro45** [comment]
Merci @jgribonvald 
Nous avons trouvé la source du problème: vous utilisez le mode strict de mariaDB que nous n'utilisions pas.
A priori, votre script python2 devait aussi tourner sans le mode strict.
Quoi qu'il en soit, nous avons mis à jour nos environnements de développement/test pour aussi utiliser ce mode.

**Comment by cdaviau** [comment]
Bonjour,
nous utilisons le mode strict en prod également, et donc avec le script en python 2.
Bonne fin de journée.

**Comment by plegay** [comment]
Je reviens sur cette issue:

La correction (V.1.1.1) a consisté à initialiser les champs timecreated et timemodified
avec la fonction now() de mysql. 
Or ces champs sont des bigint(10).
Le résultat est que la ligne ajoutée ce jour indique 20190319120906,
alors que le max des valeurs des anciennes données vaut 1544630914.
On voit de suite que l'on n'est pas avec le même format.
Les valeurs d'origine doivent être en timestamp unix généré en python et pas en datetime mysql (à vérifier).
Merci de corriger cela.

**Comment by vcastro45** [comment]
Corrigé comme suit:

https://github.com/GIP-RECIA/ESCOSynchroMoodle/blob/420fdec907b85ee56d9c4f2b56a5fc6a226c05bf/synchromoodle/dbutils.py#L1034-L1040

de la meme manière que le timestamp courant était est récupérer dans le reste de l'application (héritage de la version python2):

https://github.com/GIP-RECIA/ESCOSynchroMoodle/blob/420fdec907b85ee56d9c4f2b56a5fc6a226c05bf/synchromoodle/dbutils.py#L908-L916
